// Pruebas de humo de los flujos principales contra el build de producción (dist/), usando el handle window.__dante
import { test, expect } from '@playwright/test';
test.setTimeout(180000);
const boot = async (page) => { await page.addInitScript(() => { try { localStorage.setItem('dante-welcomed', '1'); localStorage.setItem('dante-quality', 'lite'); } catch (e) {} }); await page.goto('/index.html'); await page.waitForFunction(() => window.__dante && window.__dante.dante, null, { timeout: 30000 }); await page.evaluate(() => { const D = window.__dante; D.world.autoClock = false; D.setNight(false); D.kiaraAI.next = 9999; }); };
test('carga sin errores y construye a Dante', async ({ page }) => { const errs = []; page.on('pageerror', e => errs.push(e.message)); await boot(page); const st = await page.evaluate(() => window.__dante.dante.stats); expect(st.verts).toBeGreaterThan(5000); expect(errs).toEqual([]); });
test('trae la pelota', async ({ page }) => { await boot(page); const s = await page.evaluate(async () => { const D = window.__dante; D.dante.root.position.set(0, 0, 1); D.setState('stand', { dur: 99 }); const f0 = D.achv.fetches; D.doThrow(0, -200); const g0 = D.world.time; const t0 = performance.now(); while (performance.now() - t0 < 120000 && D.world.time - g0 < 16) { await new Promise(r => setTimeout(r, 300)); if (D.achv.fetches > f0) return 'fetched'; } return D.ai.state + ' gameSecs=' + (D.world.time - g0).toFixed(1); }); expect(s).toBe('fetched'); });
test('noche: va al kennel y llora si está cerrado', async ({ page }) => { await boot(page); const r = await page.evaluate(async () => { const D = window.__dante; D.world.kennelClosed = true; D.setNight(true); D.dante.root.position.set(-4, 0, -4); await new Promise(r => setTimeout(r, 5000)); return D.ai.state; }); expect(['cry', 'to_kennel']).toContain(r); });
test('trucos con entrenamiento al 100 salen', async ({ page }) => { await boot(page); const r = await page.evaluate(async () => { const D = window.__dante; D.stats.felicidad = 90; D.training.sit = 100; D.cmdTrick('sit'); await new Promise(r => setTimeout(r, 300)); return D.ai.state; }); expect(r).toBe('trick'); });
test('menú y logros abren', async ({ page }) => { await boot(page); await page.click('#menuBtn'); await expect(page.locator('#menu')).toHaveClass(/show/); await page.click('#menuClose'); await page.click('#title'); await expect(page.locator('#achv')).toHaveClass(/show/); });
